Fix the 80-bit float type
Introduced in d770c084ebd8 and was not correct, resulted in the
following error when we actually converted a C function that returned
long double:

    RuntimeError: LLVM IR parsing error
    <string>:331:9: error: expected type
    declare long double @"strtold"(i8* %"param1_arg", i8** %"param2_arg")
            ^